### PR TITLE
tests: add tests for KMU and keys provisioning

### PR DESCRIPTION
**Pull request by gchwier**
Add two test applications with test scenarios automated with pytest. 
Frist: verify_west_ncs_provision - application with hardcoded keys only to check if command `west ncs-provission` writes proper keys.
Second: hello_for_kmu - hello_world based app with MCUboot,  keys are uploaded with west command and application is flashed. Checked if app is booted when using correct keys and not booted with wrong keys.
 
To test one can use command:
`${ZEPHYR_BASE}/scripts/twister --device-testing -p nrf54l15dk/nrf54l15/cpuapp --device-serial /dev/ttyACM1 --west-flash="--erase" -T tests/subsys/kmu  -vv --no-clean`

### CODE REVIEW

**Review by nordicjm — APPROVED** [review]

**Comment by gchwier** [comment]
failed after rebasing to https://github.com/nrfconnect/sdk-nrf/pull/18366,
received build error:
`west build -p -b nrf54l15dk/nrf54l15/cpuapp tests/subsys/kmu/hello_for_kmu`
```
modules/nrf/subsys/nrf_security/src/libmbedcrypto_base.a(threading_alt.c.obj): in function `k_mutex_lock':
ncs/nrf/build/mcuboot/zephyr/include/generated/zephyr/syscalls/kernel.h:986: undefined reference to `z_impl_k_mutex_lock'
```

**Comment by Vge0rge** [comment]
> failed after rebasing to #18366, received build error: `west build -p -b nrf54l15dk/nrf54l15/cpuapp tests/subsys/kmu/hello_for_kmu`
> 
> ```
> modules/nrf/subsys/nrf_security/src/libmbedcrypto_base.a(threading_alt.c.obj): in function `k_mutex_lock':
> ncs/nrf/build/mcuboot/zephyr/include/generated/zephyr/syscalls/kernel.h:986: undefined reference to `z_impl_k_mutex_lock'
> ```

Hey, can you try to rebase on this and see if it fixes your build issue?
https://github.com/nrfconnect/sdk-nrf/pull/18487

**Review by nvlsianpu — APPROVED** [review]
