### PR TITLE
boards: Select SDC for nRF54LM20A board

### PR DESCRIPTION
**Pull request by doki-nordic**
Commit https://github.com/nrfconnect/sdk-nrf/commit/b828ce71eafcfa3a00300226ac970adc1c725b0e enabled `bt_hci_sdc` and disabled `bt_hci_controller`, but `bt_hci_controller` is still set as the default controller.  
 
This commit updates the configuration to select `bt_hci_sdc` as the default controller.

### CODE REVIEW

**Review by kl-cruz — APPROVED** [review]

**Review by maje-emb — APPROVED** [review]

**Review by grochu — APPROVED** [review]

**Comment by gchwier** [comment]
I've tried to build smp_svr:
`west build -p -b nrf54lm20apdk/nrf54lm20a/cpuapp $ZEPHYR_BASE/samples/subsys/mgmt/mcumgr/smp_svr -T sample.mcumgr.smp_svr.bt  -d build-54lm-smpsvr`

and received:
```
FAILED: modules/nrf/subsys/mpsl/init/CMakeFiles/..__nrf__subsys__mpsl__init.dir/mpsl_init.c.obj 
...
In file included from /home/grch/ncs/zephyr/include/zephyr/toolchain.h:50,
                 from /home/grch/ncs/zephyr/include/zephyr/sys/util.h:18,
                 from /home/grch/ncs/zephyr/include/zephyr/init.h:13,
                 from /home/grch/ncs/nrf/subsys/mpsl/init/mpsl_init.c:7:
/home/grch/ncs/zephyr/include/zephyr/toolchain/gcc.h:87:36: error: static assertion failed: "Currently mpsl only works when frequency is 128MHz"
   87 | #define BUILD_ASSERT(EXPR, MSG...) _Static_assert((EXPR), "" MSG)
      |                                    ^~~~~~~~~~~~~~
/home/grch/ncs/nrf/subsys/mpsl/init/mpsl_init.c:166:1: note: in expansion of macro 'BUILD_ASSERT'
  166 | BUILD_ASSERT(NRF_CONFIG_CPU_FREQ_MHZ == 128, "Currently mpsl only works when frequency is 128MHz");
      | ^~~~~~~~~~~~
```
do I missed something?

**Comment by gchwier** [comment]
works with target: `nrf54lm20apdk@0.2.0/nrf54lm20a/cpuapp`
