### PR TITLE
samples: cellular: modem_shell: Fix P-GPS+CoAP

### PR DESCRIPTION
**Pull request by trantanen**
Hopefully this is a temporary fix for regression caused by PR #17634, where `CONFIG_NRF_CLOUD_COAP_DOWNLOADS` was enabled by default for FOTA and P-GPS configurations.
Disabling `CONFIG_NRF_CLOUD_COAP_DOWNLOADS` for now until the dependencies are clarified.
The fix is needed urgently to fix the CI which runs P-GPS+CoAP configuration. Adding this to sample.yaml too.

The error after PR #17634 looks as follows:
```
                 from /jenkins_workspace/workspace/nnect-nrf-iot_mosh_images_master/nrf/subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c:7:
/jenkins_workspace/workspace/nnect-nrf-iot_mosh_images_master/zephyr/include/zephyr/toolchain/gcc.h:87:36: error: static assertion failed: "CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE should be at least 80 for CoAP P-GPS downloads"
```

After setting `CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=80` in `overlay-cloud_coap.conf` linking fails:
```
/home/tor1/work/ncs/nrf/subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c:76: undefined reference to `fota_download_external_evt_handle'
/home/tor1/work/ncs/nrf/subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c:296: undefined reference to `fota_download_external_start'

```

This can be fixed with `CONFIG_FOTA_DOWNLOAD_EXTERNAL_DL` but sounds like this dependency should be handled somewhere when `CONFIG_NRF_CLOUD_COAP_DOWNLOADS` is defined.
`CONFIG_NRF_CLOUD_FOTA_POLL` has this: `select FOTA_DOWNLOAD_EXTERNAL_DL if NRF_CLOUD_COAP_DOWNLOADS`
But we don't have `CONFIG_NRF_CLOUD_FOTA` or `CONFIG_NRF_CLOUD_FOTA_POLL`.

### CODE REVIEW

**Review by jhirsi — APPROVED** [review]

**Review by jtguggedal — APPROVED** [review]

**Review by jayteemo — APPROVED** [review]
i'll address the nrf_cloud lib issue today.

**Comment by jayteemo** [comment]
this should be fixed by https://github.com/nrfconnect/sdk-nrf/pull/17917

for this PR, you will still need to set `CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=80` in `overlay-cloud_coap.conf`

**Comment by trantanen** [comment]
> for this PR, you will still need to set `CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=80` in `overlay-cloud_coap.conf`

Should not be necessary when `CONFIG_NRF_CLOUD_COAP_DOWNLOADS=n`.
I plan to remove `CONFIG_NRF_CLOUD_COAP_DOWNLOADS=n` and add `CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=80` once PR #17917 gets merged. That I can do with a separate PR. The intention with this PR was to get our build fixed quickly but seems no merges have been occurring today.

**Comment by jayteemo** [comment]
> That I can do with a separate PR

yes, sorry, i was implying that this PR could just fix the option len issue, since the build error is fixed by #17917.
whatever is easier.  i see you've already put in a merge request.
